name: VyOS Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: UTC
      BUILDER_REFS: 1.4.0-epa2
      RELEASE_TRAIN: sagitta
      RELEASE_VERSION: 1.4
      

    steps:
    - name: Set env
      run: |
        env
        echo "BUILD_VERSION=${RELEASE_VERSION}-rolling-$(date -u +%Y%m%d%H%M)" >> "$GITHUB_ENV"

    - name: git clone vyos-build
      run: |
        set -eux

        git clone --branch "$BUILDER_REFS" --single-branch https://github.com/vyos/vyos-build.git vyos-build
        cd vyos-build
        git checkout -B "$BUILDER_REFS"

    - id: build_iso
      name: Build iso
      run: |
        set -eux

        mkdir ./vyos-build/build/

        docker image pull docker.io/vyos/vyos-build:"$RELEASE_TRAIN"

        docker container run --rm --privileged -v "$PWD"/vyos-build/:/vyos -w /vyos docker.io/vyos/vyos-build:"$RELEASE_TRAIN" \
        sudo --preserve-env \
        ./build-vyos-image \
          --architecture amd64 \
          --build-type release \
          --version "$BUILD_VERSION" \
          iso \
        ;

        ls -al ./vyos-build/build/

        mv ./vyos-build/build/live-image-amd64.hybrid.iso ./vyos-"$BUILD_VERSION"-amd64.iso


    - id: upload_iso_artifact
      name: "Uploading artifacts: ISO image to GitHub"
      uses: actions/upload-artifact@v4
      with:
        name: vyos-${{ env.BUILD_VERSION }}-amd64.iso
        path: ./vyos-${{ env.BUILD_VERSION }}-amd64.iso
        retention-days: 30
        if-no-files-found: error


    - id: publish_release
      name: "Release publishing: publish release"
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.BUILD_VERSION }}
        fail_on_unmatched_files: true
        files: |
          ./vyos-${{ env.BUILD_VERSION }}-amd64.iso

